_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix: /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix: /_profiler

list_order:
    path: /orders
    controller: App\Action\ListOrders

order_cancel:
    path: /orders/{id}/cancel
    controller: App\Action\CancelOrder

list_order_status:
    path: /order_status
    controller: App\Action\ListOrderStatus
